<?php

return [
    'textfile_paths' => [
        'Bilar Breeder Local' => '\\\\172.16.220.1\\Programs\\NAV_TEXTFILE_AR\\BILAR_BREEDER',
        'Bilar Breeder'       => '\\\\172.16.220.1\\Programs\\NAV_TEXTFILE_AR\\BILAR_BREEDER',
        'Gp Jagna'            => '\\\\172.16.112.51\\NAV_TEXTFILE_AR\\GP_JAGNA',
        'Ice Plant'           => '\\\\172.16.184.49\\textfile\\NAV_TEXTFILE_AR\\ICE_PLANT',
        'Peanut Kisses'       => '\\\\172.16.184.49\\textfile\\NAV_TEXTFILE_AR\\PEANUT_KISSES',
        'Cortes Poultry'      => '\\\\172.16.192.68\\nav-textfile\\NAV_TEXTFILE_AR\\CORTES_POULTRY',
        'Cortes Piggery'      => '\\\\172.16.192.68\\nav-textfile\\NAV_TEXTFILE_AR\\CORTES_PIGGERY',
        'Canhayupon Breeder'  => '\\\\172.16.220.223\\Canhayupon_database\\NAV_TEXTFILE_AR\\CANHAYUPON',
        'Bilar Hatchery'      => '\\\\172.16.219.200\\Programs\\NAV_TEXTFILE_AR\\BILAR_HATCHERY',
        'Lapsaon Breeder'     => '\\\\172.16.220.222\\database_lapsaon\\NAV_TEXTFILE_AR\\LAPSAON',
        'Rizal Breeder'       => '\\\\172.16.217.11\\Rizal_Breeder\\NAV_TEXTFILE_AR\\RIZAL_BREEDER',
        // ubay server 
        'Feedmill'            => '\\\\172.16.104.1\\nav-textfile\\NAV_TEXTFILE_AR\\FEEDMILL',
        'Growout'             => '\\\\172.16.104.1\\nav-textfile\\NAV_TEXTFILE_AR\\GROWOUT',
        'Cortes Fertilizer'   => '\\\\172.16.104.1\\nav-textfile\\NAV_TEXTFILE_AR\\CORTES_FERTILIZER',
        'Ubay Fertilizer'     => '\\\\172.16.104.1\\nav-textfile\\NAV_TEXTFILE_AR\\UBAY_FERTILIZER',
        'Piggery Untaga'      => '\\\\172.16.104.1\\nav-textfile\\NAV_TEXTFILE_AR\\PIGGERY_UNTAGA',
        'Demo Farm'           => '\\\\172.16.104.1\\nav-textfile\\NAV_TEXTFILE_AR\\DEMOFARM',
        'Dressing Plant'      => '\\\\172.16.104.1\\nav-textfile\\NAV_TEXTFILE_AR\\DRESSING_PLANT',
        'Farmers Market'      => '\\\\172.16.104.1\\nav-textfile\\NAV_TEXTFILE_AR\\FARMERS_MARKET',
        'Meat Processing'     => '\\\\172.16.104.1\\nav-textfile\\NAV_TEXTFILE_AR\\MEAT_PROCESSING',
        'Rendering'           => '\\\\172.16.104.1\\nav-textfile\\NAV_TEXTFILE_AR\\RENDERING',
    ],

    'backup_paths' => [
        'Bilar Breeder Local' => '\\\\172.16.43.27\\Farms Team\\IT-ERL\\BREEDER AR DATABASE BACKUP\\LOCAL DEV',
        'Bilar Breeder'       => '\\\\172.16.43.27\\Farms Team\\IT-ERL\\BREEDER AR DATABASE BACKUP\\BILAR',
        'Gp Jagna'            => '\\\\172.16.43.27\\Farms Team\\IT-ERL\\BREEDER AR DATABASE BACKUP\\GP JAGNA',
        'Ice Plant'           => '\\\\172.16.43.27\\Farms Team\\IT-ERL\\BREEDER AR DATABASE BACKUP\\ICE PLANT',
        'Peanut Kisses'       => '\\\\172.16.43.27\\Farms Team\\IT-ERL\\BREEDER AR DATABASE BACKUP\\PEANUT KISSES',
        'Cortes Poultry'      => '\\\\172.16.43.27\\Farms Team\\IT-ERL\\BREEDER AR DATABASE BACKUP\\CORTES POULTRY',
        'Cortes Piggery'      => '\\\\172.16.43.27\\Farms Team\\IT-ERL\\BREEDER AR DATABASE BACKUP\\CORTES PIGGERY',
        'Canhayupon Breeder'  => '\\\\172.16.43.27\\Farms Team\\IT-ERL\\BREEDER AR DATABASE BACKUP\\CANHAYUPON BREEDER',
        'Bilar Hatchery'      => '\\\\172.16.43.27\\Farms Team\\IT-ERL\\BREEDER AR DATABASE BACKUP\\BILAR HATCHERY',
        'Lapsaon Breeder'     => '\\\\172.16.43.27\\Farms Team\\IT-ERL\\BREEDER AR DATABASE BACKUP\\LAPSAON BILAR',
        'Rizal Breeder'       => '\\\\172.16.43.27\\Farms Team\\IT-ERL\\BREEDER AR DATABASE BACKUP\\RIZAL BREEDER',
        // ubay server 
        'Feedmill'            => '\\\\172.16.18.27\\Farms Team\\IT-MELVIN\\AR DATABASE BACKUP\\FEEDMILL',
        'Growout'             => '\\\\172.16.18.27\\Farms Team\\IT-MELVIN\\AR DATABASE BACKUP\\GROWOUT',
        'Cortes Fertilizer'   => '\\\\172.16.18.27\\Farms Team\\IT-MELVIN\\AR DATABASE BACKUP\\CORTES FERTILIZER',
        'Ubay Fertilizer'     => '\\\\172.16.18.27\\Farms Team\\IT-MELVIN\\AR DATABASE BACKUP\\UBAY FERTILIZER',
        'Piggery Untaga'      => '\\\\172.16.18.27\\Farms Team\\IT-MELVIN\\AR DATABASE BACKUP\\PIGGERY UNTAGA',
        'Demo Farm'           => '\\\\172.16.18.27\\Farms Team\\IT-MELVIN\\AR DATABASE BACKUP\\DEMO FARM',
        'Dressing Plant'      => '\\\\172.16.18.27\\Farms Team\\IT-MELVIN\\AR DATABASE BACKUP\\DRESSING PLANT',
        'Farmers Market'      => '\\\\172.16.18.27\\Farms Team\\IT-MELVIN\\AR DATABASE BACKUP\\FARMERS MARKET',
        'Meat Processing'     => '\\\\172.16.18.27\\Farms Team\\IT-MELVIN\\AR DATABASE BACKUP\\MEAT PROCESSING',
        'Rendering'           => '\\\\172.16.18.27\\Farms Team\\IT-MELVIN\\AR DATABASE BACKUP\\RENDERING',
    ],
];
